export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const PUSH_PAID_ORDER = "PUSH_PAID_ORDER";
export const PUSH_PAID_ORDER_START = "PUSH_PAID_ORDER_START";
export const PUSH_PAID_ORDER_SUCCESS = "PUSH_PAID_ORDER_SUCCESS";
export const PUSH_PAID_ORDER_FAIL = "PUSH_PAID_ORDER_FAIL";
